### ISSUE TITLE
Is this the same with Matlab default tsne.m?

### ISSUE THREAD

**Issue by brianpenghe** [diego898/matlab-utils#1]
Hi Diego,
Matlab2017a introduced a tsne.m https://www.mathworks.com/help/stats/tsne.html.
Is that the same as this one? Could I ask about the source of your tsne.m?

I'm using Matlab2016b now which doesn't have tsne.m installed so I'm checking out your script.

Thanks,

**Comment by diego898** [comment]
Hello! 

I don't think so - the `tsne` in this repository is from the the `drtoolbox`: https://lvdmaaten.github.io/drtoolbox/

which is no longer being actively maintained.

**Comment by brianpenghe** [comment]
OK. Thank you!
